name = "DSMC"
uuid = "8326329c-ff1c-43cd-933f-ef0ca9f30f5b"
authors = ["Leo Basov <leo.basov@dlr.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
